### ISSUE TITLE
Different number of latent vector data is returned from vrae.transform()

### ISSUE THREAD

**Issue by saniazahan** [tejaslodaya/timeseries-clustering-vae#11]
Hi, I am passing a train data (400091*298) and test data (16487*298) vrae.transform() but getting back (40064*20) and (16480*20).
Could you please tell me why the number of sample is reduced. I didn't change anything in the model. Just fitted with my train data

**Comment by flo3003** [comment]
This problem happens with the original data too. 
In [15]: np.size(X_val,0)
Out[15]: 950

and

In [17]: np.size(z_run,0)
Out[17]: 928

**Comment by joanPlepi** [comment]
> Hi, I am passing a train data (400091_298) and test data (16487_298) vrae.transform() but getting back (40064_20) and (16480_20).
> Could you please tell me why the number of sample is reduced. I didn't change anything in the model. Just fitted with my train data

The DataLoader from PyTorch cut examples from the dataset, so it can be a number that can be divided by the batch size.
