### ISSUE TITLE
Incorrect indexing in the forward pass of the encoder

### ISSUE THREAD

**Issue by n-gao** [tejaslodaya/timeseries-clustering-vae#3]
Hi,
you made a mistake when indexing the last output of your recurrent unit in the forward pass of the Encoder. You indexed:
```
h_end = h_end[0, :, :]
```
However, according to the [documentation](https://pytorch.org/docs/stable/_modules/torch/nn/modules/rnn.html) of PyTorch's recurrent layers you should have used the very last output. You only consider the first data point of every time series.

It should have been (if I am not mistaken):
```
h_end = h_end[-1]
```

**Comment by elanter** [comment]
@n-gao Agreed - also immediately popped up when I reviewed the code (otherwise excellent implementation though!)

Given the way torch RNNs output hidden states, the last one should be the following (just ever so slightly more verbose than above comment: 
h_end = h_end[-1, :, :]

**Comment by kayuksel** [comment]
Hello @n-gao, I am also based in Munich. Please, contact me from `kamer.yueksel@hawk.ai` if you would be interested in e.g. student-working opportunities or just to get to know each other.

**Comment by tejaslodaya** [comment]
You're correct @n-gao . It was a miss on my side.
I'm merging your PR.

@kayuksel removing your comment because it was publicity. Please contact him/her directly.
