### ISSUE TITLE
VAR for multi-class classification

### ISSUE THREAD

**Issue by HankKung** [tejaslodaya/timeseries-clustering-vae#8]
Hi thanks for your great work, it's elegant!

I'm trying to make a VAE for classification by replacing loss_fn with nn.CrossEntropyLoss() and num_output_feature with num_class. I'm not quite sure if it is correct. Is it equivalent to the k-means you mentioned in FAQ?

**Comment by tejaslodaya** [comment]
@HankKung why did you close this?

Did you find a workaround?

**Comment by HankKung** [comment]
> @HankKung why did you close this?
> 
> Did you find a workaround?

Not yet. I thought I misunderstood how it works. I'm attempting to apply it on log key sequence for anomaly detection.
